repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker
    rev: 1.0.1
    hooks:
      - id: black-disable-checker
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: 93b15ca
    hooks:
      - id: pydocstringformatter
        args:
          [
            --style=numpydoc,
            --no-numpydoc-name-type-spacing,
            --no-final-period,
            --no-capitalize-first-letter,
          ]
